name: Bug Report

on:
  issues:
    types:
      - opened
      - edited
      - labeled

jobs:
  bug_report:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Required Information
        run: |
          if [ -z "${{ github.event.issue.title }}" ]; then
            echo "Please provide a descriptive issue title."
            exit 1
          fi

          if [ -z "${{ github.event.issue.body }}" ]; then
            echo "Please provide a detailed issue description."
            exit 1
          fi

          if [ -z "${{ github.event.issue.labels }}" ]; then
            echo "Please apply relevant labels to categorize the issue."
            exit 1
          fi

      - name: Notify Maintainers
        run: |
          echo "A new bug report has been submitted. Please review it."
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} # If you use Slack for notifications, set up a secret for your webhook URL

      - name: Add Labels
        run: |
          # Automatically add labels based on the issue content
          # Example: Use keywords in the issue title or body to categorize the issue.
          # Example: You can also manually apply labels on GitHub.

      - name: Assign to Developer
        run: |
          # Automatically assign the issue to a developer based on project policies.
          # Example: Assign based on team rotation or expertise.

      - name: Close if Duplicate
        run: |
          # Check if the issue is a duplicate of an existing one.
          # Example: Search for duplicate issues and close this one if needed.
